name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Install dependencies for all workspaces
      - name: Install root dependencies
        run: npm install

      - name: Install API dependencies
        working-directory: ./api
        run: npm install

      - name: Install Web dependencies
        working-directory: ./web
        run: npm install

      # Lint and format checks
      - name: Lint API
        working-directory: ./api
        run: npm run lint

      - name: Lint Web
        working-directory: ./web
        run: npm run lint

      - name: Check API formatting
        working-directory: ./api
        run: npx prettier --check "src/**/*.ts" "test/**/*.ts"

      - name: Check Web formatting
        working-directory: ./web
        run: npm run format:check

      # Build projects
      - name: Build API
        working-directory: ./api
        run: npm run build

      - name: Build Web
        working-directory: ./web
        run: npm run build

